### PR TITLE
Greek Translations

### PR DESCRIPTION
**Pull request by mackonsti**
Adding Greek Translations (Part 1)

### CODE REVIEW

**Comment by mackonsti** [comment]
There was some version of index.yml that contained keys:
```
noCameraAccess:
noCameraFound:
safariSupportOnly:
```
...but could not find them now, are they removed @marvinsxtr ? Thanks

**Comment by marvinsxtr** [comment]
@mackonsti I forgot that they are on the dev branch. Please also add the translations for them

**Comment by mackonsti** [comment]
Added, thanks. A bunch of questions:
- How would you say Impressum (DE) or Imprint (EN) as a synonym? I cannot find some exact translation.
- What is TMG in the imprint text? An acronym of..?
- Do we keep key `creditsTranslation` especially the part of the URL (free version)? I have kept it anyway.
- What do you mean with "Note that selecting a file directly from camera is not supported." in `selectCertificateDescription` (index.yml) ? Select a file from the camera, the actual camera? How on earth can this be done 🤣 I guess you're trying to make it simple for people who think they can upload files via the camera feature?
Danke!

**Comment by marvinsxtr** [comment]
* For imprint, you can use "legal note" as a synonym. 
* TMG is "Telemediengesetz" in German I believe. 
* Keep the `creditsTranslation` part with the link to deepl, I translated some parts of the Finnish translation with it and use it for single missing keys.
* Yeah, I tried to explain that it is not possible to select a file and the choose to take a picture.

**Comment by mackonsti** [comment]
Hi @marvinsxtr I have updated the last and hardest translation part for GDPR as well as some fixes based on your comments. I have triple-checked everything and we are good to go. When you have time, let me know if-when you push these to production. Thank you again very much for your help and patience, happy to have helped.

**Comment by marvinsxtr** [comment]
@mackonsti The changes are now live, see #56.

**Pull request merged**
