### PR TITLE
[localisation] Added RO locale

### PR DESCRIPTION
**Pull request by KoNickss**
Added RO locale
May require changes in the future since romanian is missing some grammar parts that are required in as variables, I'll personally handle if neccesary all adaptation and changes to this localisation

### CODE REVIEW

**Comment by KoNickss** [comment]
could it still be added here? or does it need to be on the localisation branch?

**Comment by marvinsxtr** [comment]
I can still change it :)

**Comment by KoNickss** [comment]
oh ok, my bad, it's a bit late here and I wasn't paying attention when changing the branch, so sorry, won't happen again

**Comment by marvinsxtr** [comment]
Actually dev had the latest changes to localization haha

**Comment by KoNickss** [comment]
Thank you!

**Pull request merged**
