### PR TITLE
Support JPEG and other image formats; remove pngjs dependency

### PR DESCRIPTION
**Pull request by ibobo**
Hi, I found myself unable to use the tool since the IO.it government issued app is saving the Green Pass image in JPEG format and the tool didn't support it out of the box. Of course I could just make a screenshot of the QR, that's saved in PNG format, and upload that, but that's somewhat overkill for some users.

I came to look at the code and saw an easy way to support both JPEG, PNG and other popular file formats (namely WEBP and GIF) as an input, by using Canvas API only. This also makes the build project smaller since it doesn't rely on pngjs anymore.

One small caveat: I couldn't test the generation of the actual pass, but I could confirm the signing API gets called with the correct hash.

If you find any problem with my implementation please write me back, I'll be happy to fix it and allow the pull request to be merged succesfully.

### CODE REVIEW

**Review by hauketoenjes — APPROVED** [review]

**Comment by hauketoenjes** [comment]
Hi, thanks for your contribution.

The main problem, I discovered with this, is the underlying qr code reader. We actually implemented different image formats a few weeks ago with basically the same approach as you, without using the canvas and instead using just the `Image()` element. 

In the tests we did back then and which I did with your code again, we discovered, that jsQR can't handle large images containing the vaccination QR Code. It works fine with screenshot's of qr codes, since they are not that large most of the time (at least in my tests). Please refer to this issue in the jsQR repository: https://github.com/cozmo/jsQR/issues/101

I also tried different QR Reader libraries (with your code), but until now, I haven't found a single one that can decode my test images (probably because many are based on [@zxing/library](https://github.com/zxing-js/library)). I also haven't found a solution for this problem.

**Maybe you have an idea**? We could try an approach to scale down the uploaded image in the user's browser. 

I also tested to scale down a JPEG image which didn't work in original size, and it works when scaled down. This confirms not only that the test image itself works, but also that jsQR has indeed a problem with large images…

**Comment by hauketoenjes** [comment]
If you have no idea on how to tackle this problem, I'll just merge this pull request the next days, since it works with images that are “small” enough 👍🏼. 

Thanks again!

**Comment by ibobo** [comment]
We could try resizing the image to a sensible amount (in total number of pixels) and then pass it to jsQR. The Italian green pass QR works fine on my iPhone, and it's a 732 x 2148 image.

I'll try to implement this ASAP.

**Comment by ibobo** [comment]
I added a constrain to 2 Mpx, and the image from the jsQR issue gets correctly decoded on my iPhone.

**Review by hauketoenjes — APPROVED** [review]

**Comment by hauketoenjes** [comment]
Thanks for your reply!

I tried the changes, and they indeed work on iPhones, which are the intended device. I just had problems with the same image in Chrome/Firefox on Linux. Actually, I don't know what the problem with jsQR is in Chrome/Firefox, and currently I have no time to further debug it, but this PR works and provides more options to upload a Vaccination-QR than we had before. 

Thanks again for your contribution 👍🏼

**Pull request merged**
